#Configuración de CrashDetectorMC
#Sun Mar 01 15:40:05 UTC 2026
color_advertencia=FFD700
api_de_registros_seleccionada=SecureLogger
color_enlace=56CCF2
0351=true
color_fondo=282828
proxy_sysout_syserr=true
color_boton=46468C
sitio_de_registros_seleccionado=https\://securelogger.net/save/log?
hmcl_carpeta=
color_info=FFFFFF
color_de_titulos_de_consolas=56CCF2
nombre_cd=CrashDetector
color_caja_texto=3C3C3C
verificaciones.lista_de_denegacion=
sito_de_informes=https\://asbestosstar.egoism.jp/crash_detector/crash_detector_servidor.rb
color_texto=FFFFFF
condenar_pirateria=false
hablicar_buscardor=true
color_error=FF6347
color_titulo=56CCF2
idioma_respaldo=es
